# Generated by Django 2.2.2 on 2020-09-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiring_token', models.TextField(max_length=50)),
                ('access_token', models.TextField(max_length=50)),
            ],
        ),
    ]
