# Generated by Django 2.2.2 on 2020-09-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='user_email',
            field=models.TextField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
