# Generated by Django 2.2.2 on 2020-10-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('course_code', models.CharField(max_length=20)),
                ('score', models.IntegerField()),
                ('workload', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('review_text', models.TextField()),
                ('full_name', models.CharField(max_length=100)),
                ('study_programme', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
