# Generated by Django 2.2.2 on 2020-10-23 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_review_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='review_count',
        ),
    ]
