# Generated by Django 2.2.2 on 2020-10-23 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_average_review_score'),
        ('course', '0003_course_pass_rate'),
    ]

    operations = [
    ]
