# Generated by Django 2.2.2 on 2020-10-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20201026_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='average_difficulty',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='course',
            name='average_workload',
            field=models.FloatField(default=-1),
        ),
    ]
